/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as SignupImport } from './routes/signup'
import { Route as LoginImport } from './routes/login'
import { Route as AuthImport } from './routes/_auth'
import { Route as AuthIndexImport } from './routes/_auth/index'
import { Route as AuthTeamImport } from './routes/_auth/team'
import { Route as AuthSitesImport } from './routes/_auth/sites'
import { Route as AuthSettingsImport } from './routes/_auth/settings'
import { Route as AuthProfileImport } from './routes/_auth/profile'
import { Route as AuthBillingImport } from './routes/_auth/billing'
import { Route as AuthAnalyticsImport } from './routes/_auth/analytics'
import { Route as AuthUserUserIdImport } from './routes/_auth/user/$userId'

// Create/Update Routes

const SignupRoute = SignupImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const AuthIndexRoute = AuthIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)

const AuthTeamRoute = AuthTeamImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthRoute,
} as any)

const AuthSitesRoute = AuthSitesImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => AuthRoute,
} as any)

const AuthSettingsRoute = AuthSettingsImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthRoute,
} as any)

const AuthProfileRoute = AuthProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthRoute,
} as any)

const AuthBillingRoute = AuthBillingImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthRoute,
} as any)

const AuthAnalyticsRoute = AuthAnalyticsImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthRoute,
} as any)

const AuthUserUserIdRoute = AuthUserUserIdImport.update({
  id: '/user/$userId',
  path: '/user/$userId',
  getParentRoute: () => AuthRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupImport
      parentRoute: typeof rootRoute
    }
    '/_auth/analytics': {
      id: '/_auth/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthAnalyticsImport
      parentRoute: typeof AuthImport
    }
    '/_auth/billing': {
      id: '/_auth/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthBillingImport
      parentRoute: typeof AuthImport
    }
    '/_auth/profile': {
      id: '/_auth/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthProfileImport
      parentRoute: typeof AuthImport
    }
    '/_auth/settings': {
      id: '/_auth/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthSettingsImport
      parentRoute: typeof AuthImport
    }
    '/_auth/sites': {
      id: '/_auth/sites'
      path: '/sites'
      fullPath: '/sites'
      preLoaderRoute: typeof AuthSitesImport
      parentRoute: typeof AuthImport
    }
    '/_auth/team': {
      id: '/_auth/team'
      path: '/team'
      fullPath: '/team'
      preLoaderRoute: typeof AuthTeamImport
      parentRoute: typeof AuthImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexImport
      parentRoute: typeof AuthImport
    }
    '/_auth/user/$userId': {
      id: '/_auth/user/$userId'
      path: '/user/$userId'
      fullPath: '/user/$userId'
      preLoaderRoute: typeof AuthUserUserIdImport
      parentRoute: typeof AuthImport
    }
  }
}

// Create and export the route tree

interface AuthRouteChildren {
  AuthAnalyticsRoute: typeof AuthAnalyticsRoute
  AuthBillingRoute: typeof AuthBillingRoute
  AuthProfileRoute: typeof AuthProfileRoute
  AuthSettingsRoute: typeof AuthSettingsRoute
  AuthSitesRoute: typeof AuthSitesRoute
  AuthTeamRoute: typeof AuthTeamRoute
  AuthIndexRoute: typeof AuthIndexRoute
  AuthUserUserIdRoute: typeof AuthUserUserIdRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAnalyticsRoute: AuthAnalyticsRoute,
  AuthBillingRoute: AuthBillingRoute,
  AuthProfileRoute: AuthProfileRoute,
  AuthSettingsRoute: AuthSettingsRoute,
  AuthSitesRoute: AuthSitesRoute,
  AuthTeamRoute: AuthTeamRoute,
  AuthIndexRoute: AuthIndexRoute,
  AuthUserUserIdRoute: AuthUserUserIdRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/analytics': typeof AuthAnalyticsRoute
  '/billing': typeof AuthBillingRoute
  '/profile': typeof AuthProfileRoute
  '/settings': typeof AuthSettingsRoute
  '/sites': typeof AuthSitesRoute
  '/team': typeof AuthTeamRoute
  '/': typeof AuthIndexRoute
  '/user/$userId': typeof AuthUserUserIdRoute
}

export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/analytics': typeof AuthAnalyticsRoute
  '/billing': typeof AuthBillingRoute
  '/profile': typeof AuthProfileRoute
  '/settings': typeof AuthSettingsRoute
  '/sites': typeof AuthSitesRoute
  '/team': typeof AuthTeamRoute
  '/': typeof AuthIndexRoute
  '/user/$userId': typeof AuthUserUserIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_auth/analytics': typeof AuthAnalyticsRoute
  '/_auth/billing': typeof AuthBillingRoute
  '/_auth/profile': typeof AuthProfileRoute
  '/_auth/settings': typeof AuthSettingsRoute
  '/_auth/sites': typeof AuthSitesRoute
  '/_auth/team': typeof AuthTeamRoute
  '/_auth/': typeof AuthIndexRoute
  '/_auth/user/$userId': typeof AuthUserUserIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/login'
    | '/signup'
    | '/analytics'
    | '/billing'
    | '/profile'
    | '/settings'
    | '/sites'
    | '/team'
    | '/'
    | '/user/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/signup'
    | '/analytics'
    | '/billing'
    | '/profile'
    | '/settings'
    | '/sites'
    | '/team'
    | '/'
    | '/user/$userId'
  id:
    | '__root__'
    | '/_auth'
    | '/login'
    | '/signup'
    | '/_auth/analytics'
    | '/_auth/billing'
    | '/_auth/profile'
    | '/_auth/settings'
    | '/_auth/sites'
    | '/_auth/team'
    | '/_auth/'
    | '/_auth/user/$userId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

const rootRouteChildren: RootRouteChildren = {
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_auth",
        "/login",
        "/signup"
      ]
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/analytics",
        "/_auth/billing",
        "/_auth/profile",
        "/_auth/settings",
        "/_auth/sites",
        "/_auth/team",
        "/_auth/",
        "/_auth/user/$userId"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/signup": {
      "filePath": "signup.tsx"
    },
    "/_auth/analytics": {
      "filePath": "_auth/analytics.tsx",
      "parent": "/_auth"
    },
    "/_auth/billing": {
      "filePath": "_auth/billing.tsx",
      "parent": "/_auth"
    },
    "/_auth/profile": {
      "filePath": "_auth/profile.tsx",
      "parent": "/_auth"
    },
    "/_auth/settings": {
      "filePath": "_auth/settings.tsx",
      "parent": "/_auth"
    },
    "/_auth/sites": {
      "filePath": "_auth/sites.tsx",
      "parent": "/_auth"
    },
    "/_auth/team": {
      "filePath": "_auth/team.tsx",
      "parent": "/_auth"
    },
    "/_auth/": {
      "filePath": "_auth/index.tsx",
      "parent": "/_auth"
    },
    "/_auth/user/$userId": {
      "filePath": "_auth/user/$userId.tsx",
      "parent": "/_auth"
    }
  }
}
ROUTE_MANIFEST_END */
